spring:
    application:
        name: motocatalog
    datasource:
        url: jdbc:mysql://db:3306/motocatalogdb
        username: develop
        password: develop
        driver-class-name: com.mysql.cj.jdbc.Driver
logging:
    level:
        root: INFO
    file:
        name: app.log
    logback:
        rollingpolicy:
            max-file-size: 1MB
